name: CI/CD

on:
  push:
    branches:
      - main # Mude para o nome da sua branch principal, se necessário
  pull_request:
    branches:
      - main # Mude para o nome da sua branch principal, se necessário

jobs:
  CI:
     uses: ./.github/workflows/CI.yml
     secrets: inherit

  CD:
     needs: CI
     uses: ./.github/workflows/CD.yml
     secrets: inherit
 
