name: CI/CD

on:
  push:
    branches:
      - main # Mude para o nome da sua branch principal, se necessário
  pull_request:
    branches:
      - main # Mude para o nome da sua branch principal, se necessário

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run CI
      uses: ./.github/workflows/CI.yml

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run CD
      uses: ./.github/workflows/cd.yml
